spring.application.name=inquiry-system

spring.datasource.url=jdbc:mysql://localhost:3306/inquiry_db
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=my-super-secret-jwt-key-for-inquiry-system-project-2026-security
jwt.expiration=3600000